export type Tool = any;
export type ToolResult = any;
export type ToolInput = any;
export type ToolDescription = any;
export type ToolFunction = any;
export type ToolPermission = any;
export type ToolContext = any;
export type ToolDefinition = any;
export type ToolOption = any;
export type ToolRegistry = any;
export type ToolPermissionContext = any;
export type ToolPermissionMode = any;
export type AgentToolProgress = any;
export type BashProgress = any;
export type MCPProgress = any;
export type REPLToolProgress = any;
export type SkillToolProgress = any;
export type TaskOutputProgress = any;
export type ToolProgressData = any;
export type WebSearchProgress = any;
export const toolName : any = (() => ({})) as any;
export const PowerShellProgress : any = (() => ({})) as any;
export type SdkWorkflowProgress = any;
export type ShellProgress = any;
