/**
 * AscendCBackend — MVP KernelBackend for Ascend C (bisheng-compiled).
 *
 * Emits the four-piece operator project scaffold derived verbatim (structure)
 * from op-examples/ (GELU) and its template source op-plugin/examples/cpp_extension.
 *
 * The four files:
 *   1. csrc/<op>_custom.asc   — kernel class + __global__ __vector__ entry + host launcher
 *   2. csrc/pybind11.asc       — PYBIND11_MODULE binding (compiled by the same bisheng call)
 *   3. setup.py                — bisheng build driver (npu-smi arch probe + ABI + dep paths)
 *   4. test_<op>.py            — golden test (numpy ref vs NPU, np.allclose)
 *
 * What is scaffolded vs placeholder:
 *   - SCAFFOLDED (faithful): includes, kernel entry signature (__global__ __vector__),
 *     Kernel<Op> class skeleton (Init/Process/CopyIn/Compute/CopyOut three-stage pipeline,
 *     BUFFER_NUM=2 double-buffer), host launcher (方式3: stream(false)+OpCommand),
 *     setup.py bisheng compile_cmd, golden-test harness structure.
 *   - PLACEHOLDER (agent fills via Read/Edit/Write): the Compute() math body
 *     (op-specific: GELU = Mul→Erf→Mul→Add→Mul; other ops differ), the numpy
 *     reference formula in test_<op>.py.
 *
 * Official grounding: memory `ascend-bisheng-compile-form`.
 *
 * M3-S3：从 AtlasHarness src/tools/ascend/AscendCBackend.ts 逐字移植（仅改导入路径
 * `./KernelBackend.js` → `./KernelBackend`，对齐 AtlasCode no-ext 导入约定）。
 */

import type {
  KernelArtifact,
  KernelBackend,
  OperatorSpec,
  ProjectFile,
  TilingHint,
} from './KernelBackend'

// ── helpers ──────────────────────────────────────────────────────────────────

/** Sanitize an op name to a valid C/Python identifier stem. */
function sanitizeOp(name: string): string {
  return (name || 'unnamed_op').replace(/[^a-zA-Z0-9_]/g, '_')
}

/** PascalCase for the kernel class: gelu → Gelu, gelu_custom → GeluCustom. */
function classStem(op: string): string {
  return op.split('_').filter(Boolean).map(s => s[0].toUpperCase() + s.slice(1)).join('')
}

// ── bisheng compile flags (baked into setup.py) ──────────────────────────────
// Per op-examples/setup.py AscendBuildExtension.build_extension. setup.py owns
// the invocation; these are the canonical flags the template emits.

/**
 * The canonical bisheng flag set (op-examples/setup.py lines 78-94).
 * npu-arch is resolved at build time by get_npu_arch() (npu-smi probe), so it
 * is NOT baked here — setup.py interpolates it. Returned for documentation /
 * future direct-bisheng backends.
 */
export const BISHENG_FLAGS = [
  '-x', 'asc',
  '-shared',
  '-fPIC',
  '-std=c++17',
] as const

// ── templates ────────────────────────────────────────────────────────────────

function kernelAsc(op: string, cls: string, tiling?: TilingHint): string {
  const tileNum = tiling?.tileNum ?? 8
  const blockDim = tiling?.blockDim ?? 8
  return `// ${op} 算子 — Ascend C 自定义算子（Vector 单元实现）
// Scaffold generated by AscendCBackend (structurally derived from op-examples/GELU).
// Compute body is a PLACEHOLDER — fill via the coding base (Read/Edit/Write).
//
// 公式: TODO — document the operator formula here
//
// 模板证据: op-examples/csrc/gelu_custom.asc
//   ascend-official/op-plugin/examples/cpp_extension/csrc/add_custom.asc
#include <torch/extension.h>
#include "torch_npu/csrc/core/npu/NPUStream.h"
#include "torch_npu/csrc/framework/OpCommand.h"
#include "kernel_operator.h"

constexpr uint32_t BUFFER_NUM = 2;  // 双缓冲

// ------------------------------ Kernel${cls} 算子类 ------------------------------
class Kernel${cls} {
public:
    __aicore__ inline Kernel${cls}() {}

    // 初始化：全局内存映射 + 缓冲队列
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR z, uint32_t totalLength)
    {
        this->blockLength = totalLength / AscendC::GetBlockNum();
        if (this->blockLength == 0) return;
        this->tileNum = ${tileNum};
        this->tileLength = this->blockLength / this->tileNum / BUFFER_NUM;
        this->xGm.SetGlobalBuffer((__gm__ half *)x + this->blockLength * AscendC::GetBlockIdx(),
                                  this->blockLength);
        this->zGm.SetGlobalBuffer((__gm__ half *)z + this->blockLength * AscendC::GetBlockIdx(),
                                  this->blockLength);
        this->pipe.InitBuffer(this->inQueueX, BUFFER_NUM, this->tileLength * sizeof(half));
        this->pipe.InitBuffer(this->outQueueZ, BUFFER_NUM, this->tileLength * sizeof(half));
    }

    __aicore__ inline void Process()
    {
        this->tileNum = ${tileNum};
        for (int32_t i = 0; i < this->tileNum; i++) {
            this->CopyIn(i);
            this->Compute(i);
            this->CopyOut(i);
        }
    }

private:
    __aicore__ inline void CopyIn(int32_t progress)
    {
        AscendC::LocalTensor<half> xLocal = this->inQueueX.AllocTensor<half>();
        AscendC::DataCopy(xLocal, this->xGm[progress * this->tileLength], this->tileLength);
        this->inQueueX.EnQue(xLocal);
    }

    __aicore__ inline void Compute(int32_t progress)
    {
        AscendC::LocalTensor<half> xLocal = this->inQueueX.DeQue<half>();
        AscendC::LocalTensor<half> zLocal = this->outQueueZ.AllocTensor<half>();
        // PLACEHOLDER — op-specific compute (see gelu_custom.asc: Mul→Erf→Mul→Add→Mul)
        AscendC::DataCopy(zLocal, xLocal, this->tileLength);
        this->outQueueZ.EnQue<half>(zLocal);
        this->inQueueX.FreeTensor(xLocal);
    }

    __aicore__ inline void CopyOut(int32_t progress)
    {
        AscendC::LocalTensor<half> zLocal = this->outQueueZ.DeQue<half>();
        AscendC::DataCopy(this->zGm[progress * this->tileLength], zLocal, this->tileLength);
        this->outQueueZ.FreeTensor(zLocal);
    }

private:
    AscendC::TPipe pipe;
    AscendC::TQue<AscendC::TPosition::VECIN, BUFFER_NUM> inQueueX;
    AscendC::TQue<AscendC::TPosition::VECOUT, BUFFER_NUM> outQueueZ;
    AscendC::GlobalTensor<half> xGm;
    AscendC::GlobalTensor<half> zGm;
    uint32_t blockLength = 0;
    uint32_t tileNum = 0;
    uint32_t tileLength = 0;
};

// ------------------------------ host launcher (方式3) ------------------------------
// 方式3（推荐）: stream(false) + OpCommand::RunOpApiV2
namespace ascendc_ops {
at::Tensor ${op}_custom(const at::Tensor &x)
{
    auto z = at::empty_like(x);
    uint32_t totalLength = 1;
    for (auto i = 0; i < x.dim(); i++) { totalLength *= x.size(i); }
    auto acl_stream = c10_npu::getCurrentNPUStream().stream(false);
    uint32_t blockDim = ${blockDim};
    ${op}_custom<<<blockDim, nullptr, acl_stream>>>(
        reinterpret_cast<__gm__ uint8_t *>(x.storage().data_ptr().get()),
        reinterpret_cast<__gm__ uint8_t *>(z.storage().data_ptr().get()),
        totalLength);
    at_npu::native::OpCommand::RunOpApiV2("ascendc_${op}", [&]() {});
    return z;
}
}  // namespace ascendc_ops

// ------------------------------ kernel entry ------------------------------
extern "C" __global__ __vector__ void ${op}_custom(GM_ADDR x, GM_ADDR z, uint32_t totalLength)
{
    Kernel${cls} op;
    op.Init(x, z, totalLength);
    op.Process();
}
`
}

function pybindAsc(op: string): string {
  return `#include <pybind11/pybind11.h>
#include <torch/extension.h>

namespace ascendc_ops {
at::Tensor ${op}_custom(const at::Tensor &x);
}

// 暴露 Ascend C 自定义算子到 Python
// 用法: from custom_ops_lib import custom_${op}; y = custom_${op}(x_npu)
PYBIND11_MODULE(custom_ops_lib, m)
{
    m.def("custom_${op}", &ascendc_ops::${op}_custom, "");
}
`
}

function setupPy(): string {
  return `# bisheng 构建脚本 —— 编译 csrc/*.asc → custom_ops_lib.so
# 适配自 op-examples/setup.py + op-plugin/examples/cpp_extension/setup.py
import os
import glob
import subprocess
import re
import sysconfig
from distutils.spawn import find_executable
import torch
import torch_npu
from torch.utils.cpp_extension import BuildExtension
from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext

BASE_DIR = os.path.dirname(os.path.realpath(__file__))
USE_NINJA = os.getenv('USE_NINJA') == '1'
source_files = glob.glob(os.path.join(BASE_DIR, "csrc", "*.asc"), recursive=True)


def get_npu_arch():
    """通过 npu-smi 探测芯片型号 → 对应 bisheng 架构参数。
    910 → dav-2201；950 → dav-3510"""
    result = subprocess.run(["npu-smi", "info"], capture_output=True, text=True, check=True)
    chip_name = None
    for line in result.stdout.split('\\n'):
        if not line.strip():
            continue
        if re.search(r'Health|NPU\\s+ID|Name|Version|\\+|---|=', line):
            continue
        match = re.search(r'^\\s*\\|?\\s*\\d+\\s*\\|?\\s*([A-Za-z0-9]+)', line)
        if match:
            chip_name = match.group(1)
            break
    if chip_name is None:
        raise RuntimeError("Failed to parse chip name from npu-smi info.")
    if '950' in chip_name:
        return 'dav-3510'
    elif '910' in chip_name:
        return 'dav-2201'
    raise RuntimeError(f"New chip model: {chip_name}, please check the corresponding arch: dav-xxx")


def get_dependency_paths():
    python_include = sysconfig.get_config_var("INCLUDEPY")
    python_lib = sysconfig.get_config_var("LIBDIR")
    torch_include_paths = __import__('torch.utils.cpp_extension', fromlist=['include_paths']).include_paths()
    torch_lib = os.path.join(os.path.dirname(torch.__file__), "lib")
    torch_npu_path = os.path.dirname(torch_npu.__file__)
    torch_npu_include = os.path.join(torch_npu_path, "include")
    torch_npu_lib = os.path.join(torch_npu_path, "lib")
    return {
        "all_includes": [*torch_include_paths, python_include, torch_npu_include],
        "all_libs": [python_lib, torch_lib, torch_npu_lib],
    }


class AscendBuildExtension(BuildExtension):
    def _check_bisheng_compiler(self):
        if not find_executable('bisheng'):
            raise RuntimeError("bisheng command not found! source <CANN>/set_env.sh first.")

    def build_extension(self, ext):
        self._check_bisheng_compiler()
        dep_paths = get_dependency_paths()
        ext_fullpath = self.get_ext_fullpath(ext.name)
        os.makedirs(os.path.dirname(ext_fullpath), exist_ok=True)

        abi_value = "1" if torch._C._GLIBCXX_USE_CXX11_ABI else "0"
        npu_arch = get_npu_arch()

        compile_cmd = [
            "bisheng",
            "-x", "asc",
            f"--npu-arch={npu_arch}",
            "-shared",
            "-fPIC",
            "-std=c++17",
            f"-D_GLIBCXX_USE_CXX11_ABI={abi_value}",
            "-ltorch_npu", "-ltorch", "-lc10",
            *ext.sources,
            "-o", ext_fullpath,
        ]
        for d in dep_paths["all_includes"]:
            compile_cmd.append(f"-I{d}")
        for d in dep_paths["all_libs"]:
            compile_cmd.append(f"-L{d}")
        self.spawn(compile_cmd)


your_ext = Extension(
    name="op_extension.custom_ops_lib",
    sources=source_files,
    language="asc",
)

setup(
    name="op_extension",
    version="0.1",
    ext_modules=[your_ext],
    packages=find_packages(),
    cmdclass={"build_ext": AscendBuildExtension.with_options(use_ninja=USE_NINJA)},
)
`
}

function testPy(op: string): string {
  return `"""TDD golden 测试 — numpy 参考实现 vs NPU 算子输出

用法:
  1. python3 setup.py build_ext    # bisheng 编译 csrc/*.asc → custom_ops_lib
  2. python3 test_${op}.py          # NPU 输出 vs numpy 参考

容差: fp16 atol=1e-2 rtol=1e-2（按需调整）
"""
import numpy as np
import torch
import torch_npu


def ${op}_ref(x_np):
    """CPU 黄金参考（numpy，公式路径独立于 NPU kernel）。
    PLACEHOLDER — 用 op 的真实公式替换（见 op-examples/test_gelu.py 的 erf 路径）。"""
    return x_np  # TODO: replace with the real operator formula


def _run_on_npu(x_cpu):
    from custom_ops_lib import custom_${op}
    x_npu = x_cpu.npu()
    y_npu = custom_${op}(x_npu)
    return y_npu.cpu().numpy()


def test_${op}_fp16():
    x_cpu = torch.randn(4096, dtype=torch.float16)
    ref = ${op}_ref(x_cpu.numpy())
    y = _run_on_npu(x_cpu)
    err = float(np.max(np.abs(y - ref)))
    assert np.allclose(y, ref, rtol=1e-2, atol=1e-2), f"max_abs_err={err}"


if __name__ == "__main__":
    test_${op}_fp16()
    print("test_${op}: PASS")
`
}

// ── backend ──────────────────────────────────────────────────────────────────

export class AscendCBackend implements KernelBackend {
  readonly id = 'ascend-c' as const

  emit(spec: OperatorSpec, tiling?: TilingHint): KernelArtifact {
    const op = sanitizeOp(spec.op_name)
    const cls = classStem(op)
    const files: ProjectFile[] = [
      { path: `csrc/${op}_custom.asc`, content: kernelAsc(op, cls, tiling) },
      { path: 'csrc/pybind11.asc', content: pybindAsc(op) },
      { path: 'setup.py', content: setupPy() },
      { path: `test_${op}.py`, content: testPy(op) },
    ]
    return {
      files,
      entry_kernel: `${op}_custom`,
      op_name: op,
      module_name: 'custom_ops_lib',
    }
  }
}
