/**
 * engine 模块唯一公共出口（STR-1 门面规则）。
 *
 * E-1 窄 spine（§8.21）落 query + pipeline + state 纵切后 re-export。ports/
 * context/coordinator/tools 随各自纵切（E-1b/E-2/E-3…）落地后在此追加 re-export。
 */
export {
  queryOneRound,
  queryAgentLoop,
  DEFAULT_AGENT_LOOP_MAX_TURNS,
  ask,
  type AgentLoopDeps,
  type AgentRoundResult,
  type AgentLoopContextConfig,
  type AgentLoopArgs,
  type AgentLoopResult,
  type AskArgs,
} from './query'
export {
  executeToolUse,
  findTool,
  runToolBatch,
  partitionToolCalls,
  classifyToolError,
  validateInputBySchema,
  buildSchemaNotSentHint,
  type PipelineDeps,
  type PermissionGate,
  type ToolHooks,
  type ToolExecutionOutcome,
  type ToolBatch,
  type ToolBatchOutcome,
  type SchemaValidationResult,
} from './pipeline'
export { EngineState, type StateUpdater } from './state'
export {
  createMcpTools,
  findMcpServerConnection,
  buildMcpToolName,
  getMcpPrefix,
  mcpInfoFromString,
  normalizeNameForMCP,
  getAllBaseTools,
  isAscendToolsEnabled,
  TOOL_PRESETS,
  parseToolPreset,
  type ToolRegistryDeps,
  type ToolPreset,
  ASYNC_AGENT_ALLOWED_TOOLS,
  INTERNAL_WORKER_TOOLS,
  ALL_AGENT_DISALLOWED_TOOLS,
  CUSTOM_AGENT_DISALLOWED_TOOLS,
  IN_PROCESS_TEAMMATE_ALLOWED_TOOLS,
  COORDINATOR_MODE_ALLOWED_TOOLS,
  TASK_OUTPUT_TOOL_NAME,
  ENTER_PLAN_MODE_TOOL_NAME,
  EXIT_PLAN_MODE_V2_TOOL_NAME,
  ASK_USER_QUESTION_TOOL_NAME,
  TASK_CREATE_TOOL_NAME,
  TASK_GET_TOOL_NAME,
  TASK_LIST_TOOL_NAME,
  TASK_UPDATE_TOOL_NAME,
  CRON_CREATE_TOOL_NAME,
  CRON_DELETE_TOOL_NAME,
  CRON_LIST_TOOL_NAME,
  CONFIG_TOOL_NAME,
  WORKFLOW_TOOL_NAME,
  REPL_TOOL_NAME,
  BASH_TOOL_NAME,
  FILE_READ_TOOL_NAME,
  FILE_EDIT_TOOL_NAME,
  FILE_WRITE_TOOL_NAME,
  GREP_TOOL_NAME,
  GLOB_TOOL_NAME,
  WEB_SEARCH_TOOL_NAME,
  WEB_FETCH_TOOL_NAME,
  TODO_WRITE_TOOL_NAME,
  NOTEBOOK_EDIT_TOOL_NAME,
  SKILL_TOOL_NAME,
  SYNTHETIC_OUTPUT_TOOL_NAME,
  TOOL_SEARCH_TOOL_NAME,
  ENTER_WORKTREE_TOOL_NAME,
  EXIT_WORKTREE_TOOL_NAME,
  TEAM_CREATE_TOOL_NAME,
  TEAM_DELETE_TOOL_NAME,
  SEND_MESSAGE_TOOL_NAME,
  TASK_STOP_TOOL_NAME,
  SHELL_TOOL_NAMES,
} from './tools'
export type {
  McpToolResult,
  McpToolClient,
  McpToolDescriptor,
  MCPServerConnection,
} from './ports/mcpClient'
export {
  AgentTool,
  runAgent,
  GENERAL_PURPOSE_AGENT,
  isBuiltInAgent,
  isCustomAgent,
  getBuiltInAgents,
  parseAgentFromMarkdown,
  getActiveAgentsFromList,
  loadAgentDefinitions,
  isForkSubagentEnabled,
  FORK_AGENT,
  buildForkedMessages,
  buildChildMessage,
  isInForkChild,
  buildWorktreeNotice,
  FORK_SUBAGENT_TYPE,
  FORK_BOILERPLATE_TAG,
  FORK_DIRECTIVE_PREFIX,
  computeChildSpawnDepth,
  filterToolsForAgent,
  resolveAgentTools,
  countToolUses,
  finalizeAgentTool,
  AGENT_TOOL_NAME,
  MAX_WORKER_SPAWN_DEPTH,
  getPrompt,
  formatAgentLine,
  type RunAgentArgs,
  type RunAgentResult,
  type AgentDefinition,
  type AgentToolResult,
  type ResolvedAgentTools,
  type InjectedAgentFile,
} from './tools'
export {
  isCoordinatorMode,
  matchSessionMode,
  getCoordinatorUserContext,
  getCoordinatorSystemPrompt,
  getCoordinatorWorkerSystemPrompt,
  getCoordinatorAgents,
  WORKER_AGENT,
} from './coordinator'
export {
  getAutoCompactThreshold,
  shouldAutoCompact,
  autoCompactIfNeeded,
  AUTOCOMPACT_BUFFER_TOKENS,
  MAX_CONSECUTIVE_AUTOCOMPACT_FAILURES,
  COMPACT_MAX_OUTPUT_TOKENS,
  compactConversation,
  getCompactPrompt,
  formatCompactSummary,
  getCompactUserSummaryMessage,
  microcompactMessages,
  buildPostCompactMessages,
  estimateMessageTokens,
  evaluateTimeBasedTrigger,
  TIME_BASED_MC_CLEARED_MESSAGE,
  TIME_BASED_MC_CONFIG_DEFAULTS,
  type AutoCompactDeps,
  type AutoCompactTrackingState,
  type AutoCompactOutcome,
  type CompactionResult,
  type CompactDeps,
  type MicrocompactDeps,
  type MicrocompactOutcome,
  type TimeBasedMCConfig,
} from './context'
// E-3 S-3a（§8.27）：config 子门面（类型面/源层/三层缓存/managedPath/configRoot）
export {
  SettingsSchema,
  type SettingsJson,
  type FieldPath,
  type ValidationError,
  type SettingsWithErrors,
  SETTING_SOURCES,
  getEnabledSettingSources,
  isSettingSourceEnabled,
  type SettingSource,
  type EditableSettingSource,
  getSessionSettingsCache,
  setSessionSettingsCache,
  getCachedSettingsForSource,
  setCachedSettingsForSource,
  getCachedParsedFile,
  setCachedParsedFile,
  resetSettingsCache,
  getPluginSettingsBase,
  setPluginSettingsBase,
  clearPluginSettingsBase,
  getManagedSettingsDir,
  getManagedSettingsDropInDir,
  getAtlasConfigHomeDir,
  mergeWith,
  settingsMergeCustomizer,
  type MergeCustomizer,
  formatZodError,
  filterInvalidPermissionRules,
  loadManagedFileSettings,
  parseSettingsFile,
  getSettingsRootPathForSource,
  getSettingsFilePathForSource,
  getRelativeSettingsFilePathForSource,
  getSettingsForSource,
  getPolicySettingsOrigin,
  updateSettingsForSource,
  getInitialSettings,
  getSettingsWithErrors,
} from './config'
