/**
 * engine 模块唯一公共出口（STR-1 门面规则）。
 *
 * E-1 窄 spine（§8.21）落 query + pipeline + state 纵切后 re-export。ports/
 * context/coordinator/tools 随各自纵切（E-1b/E-2/E-3…）落地后在此追加 re-export。
 */
export {
  queryOneRound,
  queryAgentLoop,
  DEFAULT_AGENT_LOOP_MAX_TURNS,
  ask,
  type AgentLoopDeps,
  type AgentRoundResult,
  type AgentLoopContextConfig,
  type AgentLoopArgs,
  type AgentLoopResult,
  type AskArgs,
} from './query'
export {
  executeToolUse,
  findTool,
  runToolBatch,
  partitionToolCalls,
  classifyToolError,
  validateInputBySchema,
  buildSchemaNotSentHint,
  type PipelineDeps,
  type PermissionGate,
  type ToolHooks,
  type ToolExecutionOutcome,
  type ToolBatch,
  type ToolBatchOutcome,
  type SchemaValidationResult,
} from './pipeline'
export { EngineState, type StateUpdater } from './state'
export {
  createMcpTools,
  findMcpServerConnection,
  buildMcpToolName,
  getMcpPrefix,
  mcpInfoFromString,
  normalizeNameForMCP,
} from './tools'
export type {
  McpToolResult,
  McpToolClient,
  McpToolDescriptor,
  MCPServerConnection,
} from './ports/mcpClient'
export {
  AgentTool,
  runAgent,
  GENERAL_PURPOSE_AGENT,
  isBuiltInAgent,
  isCustomAgent,
  getBuiltInAgents,
  parseAgentFromMarkdown,
  getActiveAgentsFromList,
  loadAgentDefinitions,
  isForkSubagentEnabled,
  FORK_AGENT,
  buildForkedMessages,
  buildChildMessage,
  isInForkChild,
  buildWorktreeNotice,
  FORK_SUBAGENT_TYPE,
  FORK_BOILERPLATE_TAG,
  FORK_DIRECTIVE_PREFIX,
  computeChildSpawnDepth,
  filterToolsForAgent,
  resolveAgentTools,
  countToolUses,
  finalizeAgentTool,
  AGENT_TOOL_NAME,
  MAX_WORKER_SPAWN_DEPTH,
  getPrompt,
  formatAgentLine,
  type RunAgentArgs,
  type RunAgentResult,
  type AgentDefinition,
  type AgentToolResult,
  type ResolvedAgentTools,
  type InjectedAgentFile,
} from './tools'
export { isCoordinatorMode } from './coordinator'
export {
  getAutoCompactThreshold,
  shouldAutoCompact,
  autoCompactIfNeeded,
  AUTOCOMPACT_BUFFER_TOKENS,
  MAX_CONSECUTIVE_AUTOCOMPACT_FAILURES,
  COMPACT_MAX_OUTPUT_TOKENS,
  compactConversation,
  getCompactPrompt,
  formatCompactSummary,
  getCompactUserSummaryMessage,
  microcompactMessages,
  buildPostCompactMessages,
  estimateMessageTokens,
  evaluateTimeBasedTrigger,
  TIME_BASED_MC_CLEARED_MESSAGE,
  TIME_BASED_MC_CONFIG_DEFAULTS,
  type AutoCompactDeps,
  type AutoCompactTrackingState,
  type AutoCompactOutcome,
  type CompactionResult,
  type CompactDeps,
  type MicrocompactDeps,
  type MicrocompactOutcome,
  type TimeBasedMCConfig,
} from './context'
