/**
 * engine 模块唯一公共出口（STR-1 门面规则）。
 *
 * E-1 窄 spine（§8.21）落 query + pipeline + state 纵切后 re-export。ports/
 * context/coordinator/tools 随各自纵切（E-1b/E-2/E-3…）落地后在此追加 re-export。
 *
 * S-E4（2026-09-25，M-3 门盲区收口裁定）：ports/ 下 4 个零消费者占位
 *（domainMount / featureConfig / lspStatus / promptSuggestion，各 `export {}`）
 * 已删——analytics/D 波按需重建且须实质实现（§8.52 B18）；重建时在此追加
 * re-export。现存 ports/ 实质模块：mcpClient 经本门面块导出；sessionContext /
 * sessionMemory 经域内相对 import + session 域门面导出（engine/session/index.ts）。
 * M3-S1（D-3 Ascend 独立实施波）：domainMount 重建为实质模块（DomainPackage
 * 四元挂载类型 + registerDomainMount/getDomainMount holder），经本门面块导出；
 * featureConfig/lspStatus/promptSuggestion 仍删待按需重建。
 */
export {
  queryOneRound,
  queryAgentLoop,
  DEFAULT_AGENT_LOOP_MAX_TURNS,
  ask,
  type AgentLoopDeps,
  type AgentLoopEvent,
  type AgentRoundResult,
  type AgentLoopContextConfig,
  type AgentLoopArgs,
  type AgentLoopResult,
  type AskArgs,
} from './query'
// W3-3b（§8.74.15）：AgentLoopDeps 组合根构建器（自 atlascode/compose 迁入
// engine 层——cli 公共域不反向依赖壳，壳侧 2 面经 port 注册窗，见 loopDeps
// 头注）。
export {
  createAgentLoopDeps,
  setAgentLoopDepsTeammatePoolSync,
  setAgentLoopDepsMcpConnectionsProvider,
  type AgentLoopDepsConfig,
  type AgentLoopDepsBundle,
} from './loopDeps'
export {
  executeToolUse,
  findTool,
  mergeHookPermission,
  runToolBatch,
  partitionToolCalls,
  classifyToolError,
  validateInputBySchema,
  buildSchemaNotSentHint,
  type PipelineDeps,
  type PermissionGate,
  type PermissionCallContext,
  type ToolHooks,
  type PreToolUseHookOutcome,
  type PostToolUseHookOutcome,
  type HookPermissionBehavior,
  type GateVerdict,
  type ToolExecutionOutcome,
  type ToolBatch,
  type ToolBatchOutcome,
  type SchemaValidationResult,
} from './pipeline'
export { EngineState, type StateUpdater } from './state'
export {
  createMcpTools,
  findMcpServerConnection,
  buildMcpToolName,
  getMcpPrefix,
  mcpInfoFromString,
  normalizeNameForMCP,
  shouldUseSandbox,
  getAllBaseTools,
  getToolsForDefaultPreset,
  filterToolsByDenyRules,
  getTools,
  isAscendToolsEnabled,
  // #187 注册池缺口收口（P1-C 0405 根因修点）：基础工具本体全集（惰性 getter）
  getBaseToolEntities,
  TOOL_PRESETS,
  parseToolPreset,
  type ToolRegistryDeps,
  type ToolPreset,
  ASYNC_AGENT_ALLOWED_TOOLS,
  INTERNAL_WORKER_TOOLS,
  ALL_AGENT_DISALLOWED_TOOLS,
  CUSTOM_AGENT_DISALLOWED_TOOLS,
  IN_PROCESS_TEAMMATE_ALLOWED_TOOLS,
  COORDINATOR_MODE_ALLOWED_TOOLS,
  TASK_OUTPUT_TOOL_NAME,
  ENTER_PLAN_MODE_TOOL_NAME,
  EXIT_PLAN_MODE_V2_TOOL_NAME,
  ASK_USER_QUESTION_TOOL_NAME,
  TASK_CREATE_TOOL_NAME,
  TASK_GET_TOOL_NAME,
  TASK_LIST_TOOL_NAME,
  TASK_UPDATE_TOOL_NAME,
  CRON_CREATE_TOOL_NAME,
  CRON_DELETE_TOOL_NAME,
  CRON_LIST_TOOL_NAME,
  CONFIG_TOOL_NAME,
  WORKFLOW_TOOL_NAME,
  REPL_TOOL_NAME,
  BASH_TOOL_NAME,
  FILE_READ_TOOL_NAME,
  FILE_EDIT_TOOL_NAME,
  FILE_WRITE_TOOL_NAME,
  GREP_TOOL_NAME,
  GLOB_TOOL_NAME,
  WEB_SEARCH_TOOL_NAME,
  WEB_FETCH_TOOL_NAME,
  TODO_WRITE_TOOL_NAME,
  NOTEBOOK_EDIT_TOOL_NAME,
  SKILL_TOOL_NAME,
  SYNTHETIC_OUTPUT_TOOL_NAME,
  TOOL_SEARCH_TOOL_NAME,
  ENTER_WORKTREE_TOOL_NAME,
  EXIT_WORKTREE_TOOL_NAME,
  TEAM_CREATE_TOOL_NAME,
  TEAM_DELETE_TOOL_NAME,
  SEND_MESSAGE_TOOL_NAME,
  // C 桶 ③ S-E2d（§8.66）：SNIP_TOOL_NAME seed（与 tools 根门面同口径）
  SNIP_TOOL_NAME,
  TASK_STOP_TOOL_NAME,
  SHELL_TOOL_NAMES,
  LEGACY_TOOL_NAME_ALIASES,
  // §8.67 D 波 S-E2c（LSP 域 + LSPTool 本体子波）：LSP_TOOL_NAME seed
  //（与 tools 根门面同口径，LSP 族 ⑬ 槽 materialize）
  LSP_TOOL_NAME,
} from './tools'
export type {
  McpToolResult,
  McpToolClient,
  McpToolDescriptor,
  MCPServerConnection,
} from './ports/mcpClient'
// M3-S1（D-3 Ascend 独立实施波）：domain-mount 四元挂载 port（charter Port 3，
// PRT-1 承重）— DomainPackage 类型 + registerDomainMount/getDomainMount holder
export {
  type DomainPackage,
  registerDomainMount,
  getDomainMount,
  resetDomainMountForTests,
} from './ports/domainMount'
export {
  AgentTool,
  runAgent,
  GENERAL_PURPOSE_AGENT,
  isBuiltInAgent,
  isCustomAgent,
  getBuiltInAgents,
  parseAgentFromMarkdown,
  getActiveAgentsFromList,
  loadAgentDefinitions,
  isForkSubagentEnabled,
  FORK_AGENT,
  buildForkedMessages,
  buildChildMessage,
  isInForkChild,
  buildWorktreeNotice,
  FORK_SUBAGENT_TYPE,
  FORK_BOILERPLATE_TAG,
  FORK_DIRECTIVE_PREFIX,
  computeChildSpawnDepth,
  filterToolsForAgent,
  resolveAgentTools,
  countToolUses,
  finalizeAgentTool,
  AGENT_TOOL_NAME,
  MAX_WORKER_SPAWN_DEPTH,
  getPrompt,
  formatAgentLine,
  type RunAgentArgs,
  type RunAgentResult,
  type AgentDefinition,
  type AgentToolResult,
  type ResolvedAgentTools,
  type InjectedAgentFile,
  // C 桶 ③ shell·swarm 波 S-E2b 扩 root（teammate 消息面单一出口登记）：
  // 旧 utils/messages.createUserMessage（M-1 uuid/timestamp 不变量随迁，
  // 见 query/loop.ts 头注）——swarm inProcessTeammateTask 注入支 +
  // S-E2d inProcessRunner 消费。
  createUserMessage,
} from './tools'
export {
  // C 桶 ③ S-E2d（§8.66）：D 类 3 工具本体 + TeamServices 注入接缝 +
  // sendMessageTool TeamFileLoader 接缝（组合根消费面；tools 根门面
  // 再出，本 root 按消费面显式收窄——prompt 别名 / input schema /
  // 输入输出型不出引擎面 = tools 根 team/ 块头注登记，sendMessage
  // S-E2 §8.62 先例同型）
  SnipTool,
  TeamCreateTool,
  TeamDeleteTool,
  setTeamServices,
  resetTeamServices,
  createDefaultTeamContextStore,
  setTeamFileLoader,
  resetTeamFileLoader,
} from './tools'
export {
  // §8.67 D 波 S-E2c（LSP 域 + LSPTool 本体子波）：LSPTool 本体（9 操作
  // 代码智能面；LSP 域 src/lsp/ 门面 = client 域 + 配置注入窗 + manager
  // 单例，LSP server 真配置源经 setLspServerSource 注入窗由插件域 LSP
  // 集成波注册 = 前向接缝，ENABLE_LSP_TOOL 门裁 → isEnabled =
  // isLspConnected() 自门控，组合根 baseTools 注册位 = S-E2d 回填，见
  // lsp/ 子门面头注）
  LSPTool,
} from './tools'
export {
  // W2-2b 基础（§8.74.8/§8.74.12）：注册面单一出口——36 工具本体全量 lift
  // （原仅 6 体 lifted，其余 30 体只经 tools/ 深路径可取 = tui 2b 适配器经
  // STR-1 门面收口无法合法取件）。30 体 = 36 全集 − 已 lift 5（AgentTool/
  // SnipTool/TeamCreateTool/TeamDeleteTool/LSPTool）− G-3 整裁 1
  // （RemoteTriggerTool，§8.74.28 F 类 1P 整裁）；
  // 各体逐字 C-Deep 纵切已落（§8.54-§8.68 各子波头注），本块零行为纯扩面。
  BashTool,
  ReadTool,
  EditTool,
  WriteTool,
  GlobTool,
  GrepTool,
  NotebookEditTool,
  TaskCreateTool,
  TaskGetTool,
  TaskListTool,
  TaskUpdateTool,
  TaskStopTool,
  TaskOutputTool,
  TodoWriteTool,
  CronCreateTool,
  CronDeleteTool,
  CronListTool,
  EnterWorktreeTool,
  ExitWorktreeTool,
  EnterPlanModeTool,
  ExitPlanModeV2Tool,
  WebFetchTool,
  WebSearchTool,
  ConfigTool,
  AskUserQuestionTool,
  SendMessageTool,
  ListMcpResourcesTool,
  ReadMcpResourceTool,
  ToolSearchTool,
  SkillTool,
} from './tools'
export {
  // S-E2d（§8.68 remote 波 组合根 ⑭）：mcpClientRegistry 注入接缝
  // （setMcpClientRegistry 供给 + 4 型面，组合根 mcpBridge 消费面；
  // 工具侧读面 getMcpClientRegistry 同源出，ListMcp/ReadMcp 本体消费）
  getMcpClientRegistry,
  resetMcpClientRegistry,
  setMcpClientRegistry,
  type McpClientEntry,
  type McpClientRegistry,
  type McpResourceContent,
  type McpResourceItem,
} from './tools'
export {
  // G-2（2026-09-30）：WebSearch 客户端 provider 层（bing 无 key 默认 +
  // tavily key 可选；双工具面共享主入口 runWebSearch，TUI 面经本根门面
  // 消费 = tui↛engine 深 import 纪律同型）+ 2 测试缝（transport 注入 /
  // settings 键供给方，组合根 mcpBridge 型接线面见 atlascode/compose.ts）
  BING_DEFAULT_ENDPOINT,
  TAVILY_DEFAULT_ENDPOINT,
  SearchProviderError,
  filterHitsByDomains,
  parseBingResults,
  resolveWebSearchApiKey,
  resolveWebSearchProvider,
  runWebSearch,
  setWebSearchSettingsKeyProvider,
  setWebSearchTransportForTesting,
  type WebSearchExecutionContext,
  type WebSearchHttpResponse,
  type WebSearchProvider,
  type WebSearchTransport,
  type WebSearchTransportInit,
} from './tools'
export {
  // S-E2d（§8.68 remote 波 组合根 ⑭）：MCP skill 注册窗（⑥ 核销；组合根
  // initMcpConnections 供给面）+ 2 型面（映射面在组合根 mcpBridge 消费）
  setMcpSkillCommandSource,
  resetMcpSkillCommandSource,
  type McpSkillCommandSource,
  type Command,
  type SkillCommandContext,
} from './skill'
export {
  // CLI dev 面 --skills 读面（S-C2 §8.71.1.4）：bundled 技能注册表读面
  // （写面 registerBundledSkill/clearBundledSkills 留 skill 子门面，组合根/
  // 测试面消费；cli 跨域仅消费读面，STR-1 根门面显式名）
  getBundledSkills,
} from './skill'
export {
  // CLI 公共域 S-C4（§8.71.1.4）：命令模型面读面消费（旧仓 commands.ts 705L
  // 模型面 → engine/skill 域落面，本块 = cli 跨域消费显式名）：
  //   - builtInCommandNames（cli/commands.ts registerBuiltinCommandNames
  //     注入 session 域 firstPrompt 注入窗的读源；BUILT_IN_COMMANDS 占位
  //     空集，TUI 波回填后自动生效）
  //   - getCommands（cli/setup.ts 启动预取面，旧仓 setup getCommands 预取
  //     随迁）
  //   - getSkillToolCommands / getSlashCommandToolSkills / getMcpSkillCommands
  //     （skill 命令索引三族，⑥「skill 索引调用方 = TUI/CLI 波穿线消费」
  //     核销：cli/commands.ts getSkillCommandIndex 聚合消费）
  //   - clearCommandsCache（plugin 热更 / 测试复位面）
  builtInCommandNames,
  getCommands,
  getSkillToolCommands,
  getSlashCommandToolSkills,
  getMcpSkillCommands,
  clearCommandsCache,
} from './skill'
export {
  // CLI 公共域 S-C3（§8.71.1.4）：SDK structuredIO sendRequest abort 语义
  // 错误型消费面（旧仓 utils/errors.ts AbortError 经 tools 子门面随迁，
  // cli 跨域经引擎根门面消费；STR-1 根门面显式名）
  AbortError,
} from './tools'
export {
  isCoordinatorMode,
  matchSessionMode,
  getCoordinatorUserContext,
  getCoordinatorSystemPrompt,
  getCoordinatorWorkerSystemPrompt,
  getCoordinatorAgents,
  WORKER_AGENT,
  // E-7 S-7a（§8.46）：tasks 追踪层（coordinator/tasks 域门面，按消费面
  // 显式收窄：11 个 xml 域内名（10 tag 常量 + escapeXml）不出引擎面，先例
  // coordinator/index.ts:33；§8.51 复审 A-NOTE-1 措辞订正）
  POLL_INTERVAL_MS,
  STOPPED_DISPLAY_MS,
  PANEL_GRACE_MS,
  updateTaskState,
  registerTask,
  evictTerminalTask,
  getRunningTasks,
  generateTaskAttachments,
  applyTaskOffsetsAndEvictions,
  pollTasks,
  type TaskAttachment,
  killTask,
  killShellTasksForAgent,
  isLocalShellTask,
  type LocalShellTaskState,
  type BashTaskKind,
  BACKGROUND_BASH_SUMMARY_PREFIX,
  looksLikePrompt,
  LocalShellTask,
  spawnShellTask,
  registerForeground,
  hasForegroundTasks,
  backgroundAll,
  backgroundExistingForegroundTask,
  markTaskNotified,
  unregisterForeground,
  LocalAgentTask,
  killAsyncAgent,
  killAllRunningAgentTasks,
  markAgentsNotified,
  updateAgentProgress,
  updateAgentSummary,
  completeAgentTask,
  failAgentTask,
  registerAsyncAgent,
  registerAgentForeground,
  backgroundAgentTask,
  unregisterAgentForeground,
  enqueueAgentNotification,
  isLocalAgentTask,
  isPanelAgentTask,
  queuePendingMessage,
  appendMessageToLocalAgent,
  drainPendingMessages,
  createProgressTracker,
  getTokenCountFromTracker,
  updateProgressFromMessage,
  getProgressUpdate,
  createActivityDescriptionResolver,
  type LocalAgentTaskState,
  type AgentProgress,
  type ToolActivity,
  type ProgressTracker,
  type ActivityDescriptionResolver,
  stopTask,
  StopTaskError,
  getAllTasks,
  getTaskByType,
  type TaskState,
  setTaskNotificationHandler,
  resetTaskNotificationHandler,
  enqueueTaskNotification,
  type TaskNotification,
  registerCleanup,
  runCleanupFunctions,
  createAbortController,
  createChildAbortController,
  // analytics 波 §8.69：SDK 事件队列（末棒主项；drain 消费者 = CLI 波前向接缝）
  enqueueSdkEvent,
  drainSdkEvents,
  emitTaskTerminatedSdk,
  resetSdkEventQueueForTesting,
  type SdkEvent,
} from './coordinator'
export {
  getAutoCompactThreshold,
  getEffectiveContextWindowSize,
  calculateTokenWarningState,
  isAutoCompactEnabled,
  shouldAutoCompact,
  autoCompactIfNeeded,
  AUTOCOMPACT_BUFFER_TOKENS,
  MAX_CONSECUTIVE_AUTOCOMPACT_FAILURES,
  // W2-2-pre 缺面先迁①（§8.74.2）：TUI warning 态面三常量 + 纯函数面
  WARNING_THRESHOLD_BUFFER_TOKENS,
  ERROR_THRESHOLD_BUFFER_TOKENS,
  MANUAL_COMPACT_BUFFER_TOKENS,
  type TokenWarningState,
  type TokenWarningParams,
  // F-B3（S-4）：补齐兄弟错误常量 re-export（engine/context 两枚同族常量，
  // 原根门面仅导 USER_ABORT，NOT_ENOUGH_MESSAGES 面缺 → 一致性轴订正）
  ERROR_MESSAGE_NOT_ENOUGH_MESSAGES,
  ERROR_MESSAGE_USER_ABORT,
  COMPACT_MAX_OUTPUT_TOKENS,
  compactConversation,
  getCompactPrompt,
  formatCompactSummary,
  getCompactUserSummaryMessage,
  createCompactBoundaryMessage,
  // W2-2-pre 缺面先迁②（§8.74.2 compact 4 extras 之纯函数面）
  stripImagesFromMessages,
  mergeHookInstructions,
  microcompactMessages,
  resetMicrocompactState,
  getTimeBasedMCConfig,
  buildPostCompactMessages,
  estimateMessageTokens,
  evaluateTimeBasedTrigger,
  TIME_BASED_MC_CLEARED_MESSAGE,
  TIME_BASED_MC_CONFIG_DEFAULTS,
  // D-2a S4（M5 切端）：microcompact 富面回填（旧仓 orchestrator 507L）——
  // 主线程 source 门 + cached-MC env kill-switch + 富 Result 类型 +
  // CachedMCModulePort DI 缝 + time-based 配置源注入
  isMainThreadSource,
  isCachedMicrocompactEnabled,
  setCachedMCModulePort,
  getCachedMCModulePort,
  setTimeBasedMCConfigSource,
  type CachedMCModulePort,
  type PendingCacheEdits,
  type MicrocompactResult,
  // D-2a S5（重裁范围 = 原 S7）：autoCompact model-string 便捷形的 settings 读侧注入
  setAutoCompactSettingsSource,
  // D-2a S6（M5 切端）：post-compact 清理注册表 + HIGH GAP 重体端口缝
  registerPostCompactReset,
  clearPostCompactResetsForTesting,
  runPostCompactCleanup,
  setSessionMemoryCompactPort,
  setReactiveCompactPort,
  setPartialCompactPort,
  trySessionMemoryCompaction,
  tryReactiveCompact,
  reactiveCompactOnPromptTooLong,
  partialCompactConversation,
  type PostCompactReset,
  type PartialCompactDirection,
  type TryReactiveCompactParams,
  type ReactiveCompactOutcome,
  type SessionMemoryCompactPort,
  type ReactiveCompactPort,
  type PartialCompactPort,
  // W2-2-pre 缺面先迁④（§8.74.2 context 扩面族纯谓词/投影面）
  isSnipBoundaryMessage,
  projectSnippedView,
  snipProjection,
  // D-2a S1（M5 切端）：engine context 低/中风险面回填（常量/谓词/stub/store；
  // tui 同名符号经 engineCompat 显式 engine 侧 re-export 胜双星号）
  ERROR_MESSAGE_INCOMPLETE_RESPONSE,
  isSnipMarkerMessage,
  SNIP_NUDGE_TEXT,
  isSnipRuntimeEnabled,
  shouldNudgeForSnips,
  getCachedMCConfig,
  compactWarningStore,
  suppressCompactWarning,
  // D-2a S3（M5 切端）：compact 富体回填面（PTL 重试族/token 工具/DI 端口）
  MAX_PTL_RETRIES,
  PTL_RETRY_MARKER,
  ERROR_MESSAGE_PROMPT_TOO_LONG,
  groupMessagesByApiRound,
  isPromptTooLongMessage,
  parsePromptTooLongTokenCounts,
  getPromptTooLongTokenGap,
  getAssistantMessageText,
  truncateHeadForPTLRetry,
  extractDiscoveredToolNames,
  getTokenUsage,
  getTokenCountFromUsage,
  tokenCountFromLastAPIResponse,
  roughTokenCountEstimation,
  roughTokenCountEstimationForContent,
  roughTokenCountEstimationForMessages,
  tokenCountWithEstimation,
  setCompactPorts,
  getCompactPorts,
  type CompactPorts,
  type CompactContext,
  type CompactOptions,
  type CompactProgressEvent,
  type CacheSafeParams,
  type RecompactionInfo,
  type PreCompactHookResult,
  type PostCompactHookResult,
  clearCompactWarningSuppression,
  isReactiveCompactEnabled,
  isWithheldPromptTooLong,
  isWithheldMediaSizeError,
  isReactiveOnlyMode,
  type AutoCompactDeps,
  type AutoCompactTrackingState,
  type AutoCompactOutcome,
  type CompactionResult,
  type AttachmentMessage,
  type HookResultMessage,
  type CompactDeps,
  type MicrocompactDeps,
  type MicrocompactOutcome,
  type TimeBasedMCConfig,
} from './context'
// E-3 S-3a（§8.27）：config 子门面（类型面/源层/三层缓存/managedPath/configRoot）
export {
  SettingsSchema,
  type SettingsJson,
  type FieldPath,
  type ValidationError,
  type SettingsWithErrors,
  SETTING_SOURCES,
  getEnabledSettingSources,
  isSettingSourceEnabled,
  type SettingSource,
  type EditableSettingSource,
  getSessionSettingsCache,
  setSessionSettingsCache,
  getCachedSettingsForSource,
  setCachedSettingsForSource,
  getCachedParsedFile,
  setCachedParsedFile,
  resetSettingsCache,
  getPluginSettingsBase,
  setPluginSettingsBase,
  clearPluginSettingsBase,
  getManagedSettingsDir,
  getManagedSettingsDropInDir,
  getAtlasConfigHomeDir,
  mergeWith,
  settingsMergeCustomizer,
  type MergeCustomizer,
  formatZodError,
  filterInvalidPermissionRules,
  loadManagedFileSettings,
  parseSettingsFile,
  getSettingsRootPathForSource,
  getSettingsFilePathForSource,
  getRelativeSettingsFilePathForSource,
  getSettingsForSource,
  getPolicySettingsOrigin,
  getSettingsPaths,
  updateSettingsForSource,
  getAutoModeConfig,
  getInitialSettings,
  getSettingsWithErrors,
} from './config'
// E-4 S-4c1（§8.34）：permissions L3 连接器层（规则磁盘加载/写回 + 初始上下文装配）
export {
  shouldAllowManagedPermissionRulesOnly,
  loadAllPermissionRulesFromDisk,
  getPermissionRulesForSource,
  deletePermissionRuleFromSettings,
  addPermissionRulesToSettings,
  deletePermissionRule,
  syncPermissionRulesFromDisk,
  type PermissionRuleFromEditableSettings,
} from './permissions'
// E-7 S-7b（§8.47）：scheduler 子门面（cron 解析 / scheduled_tasks CRUD /
// lease lock / jitter config / 非 React scheduler 核心；durable file-backed
// 真契约面，session-cron + chokidar + GrowthBook 整砍 = 前向接缝）
export {
  parseCronExpression,
  computeNextCronRun,
  cronToHuman,
  type CronFields,
  getCronFilePath,
  readCronTasks,
  hasCronTasksSync,
  writeCronTasks,
  addCronTask,
  removeCronTasks,
  markCronTasksFired,
  listAllCronTasks,
  nextCronRunMs,
  DEFAULT_CRON_JITTER_CONFIG,
  jitteredNextCronRunMs,
  oneShotJitteredNextCronRunMs,
  findMissedTasks,
  type CronTask,
  type CronJitterConfig,
  tryAcquireSchedulerLock,
  releaseSchedulerLock,
  type SchedulerLockOptions,
  setCronJitterConfigProvider,
  getCronJitterConfig,
  isRecurringTaskAged,
  createCronScheduler,
  buildMissedTaskNotification,
  type CronScheduler,
  setSchedulerEnv,
  getSchedulerEnv,
  resetSchedulerEnv,
  isProcessRunning,
  type SchedulerEnv,
} from './scheduler'
// E-7 S-7c（§8.48）+ S-D2a（§8.57）：worktree 子门面（agent 隔离 worktree 面
// createAgentWorktree / removeAgentWorktree / cleanupStaleAgentWorktrees +
// slug 校验 + 交互会话绑定面 + tmux 族（S-D2a 回填，Enter/ExitWorktree 工具
// 本体 S-D2b 消费）+ 本域自含 git 执行层最小真子集；hooks 面 /
// saveCurrentProjectConfig 持久化面 / copyWorktreeIncludeFiles /
// attribution hook 块 / hasWorktreeChanges / execIntoTmuxWorktree
// 全裁 = 前向接缝，见 worktree/index.ts 头注）
export {
  createAgentWorktree,
  removeAgentWorktree,
  cleanupStaleAgentWorktrees,
  validateWorktreeSlug,
  worktreeBranchName,
  type WorktreeSession,
  getCurrentWorktreeSession,
  restoreWorktreeSession,
  generateTmuxSessionName,
  createWorktreeForSession,
  keepWorktree,
  cleanupWorktree,
  parsePRReference,
  isTmuxAvailable,
  getTmuxInstallInstructions,
  createTmuxSessionForWorktree,
  killTmuxSession,
  execFileNoThrowWithCwd,
  gitExe,
  findGitRoot,
  findCanonicalGitRoot,
  getBranch,
  getDefaultBranch,
  resolveGitDir,
  resolveRef,
  readRawSymref,
  getCommonDir,
  readGitHead,
  readWorktreeHeadSha,
  isSafeRefName,
  isValidGitSha,
  parseGitConfigValue,
  parseConfigString,
  resetWorktreeGitCaches,
} from './worktree'
// E-7 S-7d d1+d2（§8.49）：session 子门面（JSONL 持久层核心：写面 Project
// 单例 + record 族 / 读面 load 族 / scanner 分块读 / sessionMemory 阈值
// 状态机 + Port 5 注入窗口 / SessionEnv 注入窗口 / d2 搜索文本面 + 恢复
// 处理面 + Port 1 真契约；裁面与 H6 前向接缝见 session/index.ts +
// 各内部文件头注）。显式名块（D-1 审视订正：其余子门面块先例，名字面
// = session/index.ts 门面全量）。
export {
  type UUID,
  type AgentId,
  type SessionId,
  type Message,
  type Transcript,
  type SystemCompactBoundaryMessage,
  type SerializedMessage,
  type LogOption,
  type SummaryMessage,
  type CustomTitleMessage,
  type AiTitleMessage,
  type LastPromptMessage,
  type TaskSummaryMessage,
  type TagMessage,
  type AgentNameMessage,
  type AgentColorMessage,
  type AgentSettingMessage,
  type PRLinkMessage,
  type ModeEntry,
  type PersistedWorktreeSession,
  type WorktreeStateEntry,
  type ContentReplacementEntry,
  type ContentReplacementRecord,
  type TranscriptMessage,
  type Entry,
  sortLogs,
  type SessionEnv,
  setSessionEnv,
  getSessionEnv,
  resetSessionEnv,
  getProjectDir,
  getProjectsDir,
  getTranscriptPath,
  getTranscriptPathForSession,
  MAX_TRANSCRIPT_READ_BYTES,
  setAgentTranscriptSubdir,
  clearAgentTranscriptSubdir,
  getAgentTranscriptPath,
  getUserType,
  getEntrypoint,
  getGitBranch,
  getVersion,
  parseJSONL,
  jsonParse,
  jsonStringify,
  SKIP_PRECOMPACT_THRESHOLD,
  readTranscriptForLoad,
  isTranscriptMessage,
  isChainParticipant,
  isLegacyProgressEntry,
  isEphemeralToolProgress,
  isCompactBoundaryMessage,
  type LegacyProgressEntry,
  LITE_READ_BUF_SIZE,
  unescapeJsonString,
  extractLastJsonStringField,
  projectInstance,
  resetProjectFlushStateForTesting,
  resetProjectForTesting,
  setSessionFileForTesting,
  type TeamInfo,
  isLoggableMessage,
  cleanMessagesForLogging,
  recordTranscript,
  recordSidechainTranscript,
  recordContentReplacement,
  resetSessionFilePointer,
  adoptResumedSessionFile,
  flushSessionStorage,
  restoreSessionMetadata,
  clearSessionMetadata,
  cacheSessionTitle,
  saveMode,
  reAppendSessionMetadata,
  COMMAND_NAME_TAG,
  getFirstMeaningfulUserMessageTextContent,
  extractFirstPrompt,
  // S-C4（§8.71.1.4）：内建命令名集合注入窗（CLI 波注入口回填；cli 域
  // cli/commands.ts registerBuiltinCommandNames 消费）
  setBuiltinCommandNamesSource,
  resetBuiltinCommandNamesSourceForTesting,
  removeExtraFields,
  buildConversationChain,
  loadTranscriptFromFile,
  loadTranscriptFile,
  getSessionMessages,
  clearSessionMessagesCache,
  primeSessionMessages,
  hasSessionMessagesCache,
  doesMessageExistInSession,
  type SessionMemoryConfig,
  DEFAULT_SESSION_MEMORY_CONFIG,
  getLastSummarizedMessageId,
  setLastSummarizedMessageId,
  markExtractionStarted,
  markExtractionCompleted,
  waitForSessionMemoryExtraction,
  setSessionMemoryPort,
  getSessionMemoryPort,
  getSessionMemoryContent,
  setSessionMemoryConfig,
  getSessionMemoryConfig,
  recordExtractionTokenCount,
  isSessionMemoryInitialized,
  markSessionMemoryInitialized,
  hasMetInitializationThreshold,
  hasMetUpdateThreshold,
  getToolCallsBetweenUpdates,
  resetSessionMemoryState,
  type SessionMemoryPort,
  // d2（§8.49）：搜索文本面 + 恢复处理面 + Port 1 真契约
  type RenderableMessage,
  // E-wave-end S-E2 A7（§8.52）：Port 1 注入窗口（壳实现 + compose 注入
  // 接缝兑现；镜像 Port 5 setSessionMemoryPort 窗口先例）
  setSessionContextPort,
  getSessionContextPort,
  resetSessionContextPort,
  INTERRUPT_MESSAGE,
  INTERRUPT_MESSAGE_FOR_TOOL_USE,
  renderableSearchText,
  toolUseSearchText,
  toolResultSearchText,
  type ResumeLoadResult,
  type ProcessedResume,
  processResumedConversation,
  type SessionSnapshot,
  type SessionContextPort,
} from './session'
export {
  parseBaseToolsFromCLI,
  parseToolListFromCLI,
  initialPermissionModeFromCLI,
  initializeToolPermissionContext,
  shouldDisableBypassPermissions,
  isBypassPermissionsModeDisabled,
  createDisabledBypassPermissionsContext,
  prepareContextForPlanMode,
  type DangerousPermissionInfo,
} from './permissions'
// E-4 S-4c2（§8.35）：persist 族 + createReadRuleSuggestion（域叶约束 → L3 层）
export {
  supportsPersistence,
  persistPermissionUpdate,
  persistPermissionUpdates,
  createReadRuleSuggestion,
} from './permissions'
// E-4 S-4d（§8.36）+ S-E1 I-1 换回（§8.52 A1）：权限门工厂（base
// hasPermissionsToUseTool 全决策体 → pipeline PermissionGate 3 值 verdict）
export { createPermissionGate } from './permissions'
// E-5 S-5a（§8.39）：hooks L3 连接器层（ToolHooks 适配器 C-6 消费支 + loop stop hooks 消费面 C-4）
export {
  createToolHooks,
  createLoopHooks,
  type LoopHooks,
  type ToolHooksAdapterOptions,
} from './hooks'
// E-5 S-5b（§8.40）：流式执行核心（执行循环在域叶 src/hooks/streaming.ts；L3 re-export 面；
// 消费面 = loop 流式 chatStream E-1b-full 前向接缝，loop.ts 头注登记）
export { runHooksStream, type HookStreamYield } from './hooks'
// E-3 S-3c（§8.28）：hooks 字段族 + snapshot/provider + managedEnv
export {
  HookCommandSchema,
  HookMatcherSchema,
  HooksSchema,
  type CommandHookCommand,
  type PromptHookCommand,
  type AgentHookCommand,
  type HttpHookCommand,
  type ConfigHookCommand,
  type ConfigHookMatcher,
  type HooksSettings,
  captureHooksConfigSnapshot,
  updateHooksConfigSnapshot,
  getHooksConfigFromSnapshot,
  resetHooksConfigSnapshot,
  shouldAllowManagedHooksOnly,
  shouldDisableAllHooksIncludingManaged,
  createHooksConfigProvider,
  applySafeConfigEnvironmentVariables,
  applyConfigEnvironmentVariables,
  SAFE_ENV_VARS,
  // E-3 S-3d（§8.29）：autoCompact env 覆写读侧（config 面收拢）
  getAutoCompactEnvOverrides,
  type AutoCompactEnvOverrides,
} from './config'
// E-7 S-7e d1（§8.50）：messaging 跨会话通信域（文件式队友信箱 54 导出面 +
// 队友身份无状态层 + 域内小工具面；裁面/类型面 delta 登记见 messaging/
// 各文件头注 + 域门面 messaging/index.ts）。SEND_MESSAGE_TOOL_NAME 不出引擎
// 面：引擎级工具名单一源 = tools 域 toolNames.ts（本文件 tools 块导出）；
// messaging 域内同值常量仅域门面自持（值恒等登记见 messaging/constants.ts
// 头注），避免引擎面重名。
export {
  createTeammateContext,
  getTeammateContext,
  isInProcessTeammate,
  runWithTeammateContext,
  type TeammateContext,
  getParentSessionId,
  setDynamicTeamContext,
  clearDynamicTeamContext,
  getDynamicTeamContext,
  getAgentId,
  getAgentName,
  getTeamName,
  isTeammate,
  getTeammateColor,
  isPlanModeRequired,
  isTeamLead,
  // 尾 3 补差（C 桶 ③ shell·swarm 波 S-E2b R6；扩 root 登记见上 messaging 块头注）
  hasActiveInProcessTeammates,
  hasWorkingInProcessTeammates,
  waitForTeammatesToBecomeIdle,
  getInboxPath,
  readMailbox,
  readUnreadMessages,
  writeToMailbox,
  markMessageAsReadByIndex,
  markMessagesAsRead,
  clearMailbox,
  formatTeammateMessages,
  type TeammateMessage,
  type IdleNotificationMessage,
  createIdleNotification,
  isIdleNotification,
  type PermissionRequestMessage,
  type PermissionResponseMessage,
  createPermissionRequestMessage,
  createPermissionResponseMessage,
  isPermissionRequest,
  isPermissionResponse,
  type SandboxPermissionRequestMessage,
  type SandboxPermissionResponseMessage,
  createSandboxPermissionRequestMessage,
  createSandboxPermissionResponseMessage,
  isSandboxPermissionRequest,
  isSandboxPermissionResponse,
  PlanApprovalRequestMessageSchema,
  type PlanApprovalRequestMessage,
  PlanApprovalResponseMessageSchema,
  type PlanApprovalResponseMessage,
  ShutdownRequestMessageSchema,
  type ShutdownRequestMessage,
  ShutdownApprovedMessageSchema,
  type ShutdownApprovedMessage,
  ShutdownRejectedMessageSchema,
  type ShutdownRejectedMessage,
  createShutdownRequestMessage,
  createShutdownApprovedMessage,
  createShutdownRejectedMessage,
  sendShutdownRequestToMailbox,
  isShutdownRequest,
  isPlanApprovalRequest,
  isShutdownApproved,
  isShutdownRejected,
  isPlanApprovalResponse,
  type TaskAssignmentMessage,
  isTaskAssignment,
  type TeamPermissionUpdateMessage,
  isTeamPermissionUpdate,
  ModeSetRequestMessageSchema,
  type ModeSetRequestMessage,
  createModeSetRequestMessage,
  isModeSetRequest,
  isStructuredProtocolMessage,
  markMessagesAsReadByPredicate,
  getLastPeerDmSummary,
  formatAgentId,
  parseAgentId,
  generateRequestId,
  parseRequestId,
  createSignal,
  type Signal,
  objectGroupBy,
  extractTextContent,
  lock,
  lockSync,
  unlock,
  check,
  isHumanTurn,
  normalizeControlMessageKeys,
  collapseTeammateShutdowns,
  parseDirectMemberMessage,
  sendDirectMemberMessage,
  type DirectMessageResult,
  TEAMMATE_MESSAGE_TAG,
  TEAM_LEAD_NAME,
  PermissionModeSchema,
  type BackendType,
} from './messaging'
// E-7 S-7e d2（§8.50）：入轮命令队列层（纯内存模块级队列 + signal 订阅，
// 旧 messageQueueManager.ts 539L 逐字；logOperation 族整体裁（replay 面 =
// shell 波前向接缝）/ Permutations 删链 / ContentBlockParam 宽骨架 cast
// 收窄 / OrphanedPermission·MessageOrigin·AppState 最小形 duck 等 delta
// 登记见 messaging/queueManager.ts + queueTypes.ts 头注）
export {
  subscribeToCommandQueue,
  getCommandQueueSnapshot,
  getCommandQueue,
  getCommandQueueLength,
  hasCommandsInQueue,
  recheckCommandQueue,
  enqueue,
  enqueuePendingNotification,
  dequeue,
  dequeueAll,
  peek,
  dequeueAllMatching,
  remove,
  removeByFilter,
  clearCommandQueue,
  resetCommandQueue,
  isPromptInputModeEditable,
  isQueuedCommandEditable,
  isQueuedCommandVisible,
  popAllEditable,
  subscribeToPendingNotifications,
  getPendingNotificationsSnapshot,
  hasPendingNotifications,
  getPendingNotificationsCount,
  recheckPendingNotifications,
  dequeuePendingNotification,
  resetPendingNotifications,
  clearPendingNotifications,
  getCommandsByMaxPriority,
  isSlashCommand,
  type SetAppState,
  type PopAllEditableResult,
  type PromptInputMode,
  type EditablePromptInputMode,
  type QueuePriority,
  type QueuedCommand,
  type PastedContent,
  type OrphanedPermission,
  type MessageOrigin,
  type ImageDimensions,
  type AppState,
} from './messaging'

// §8.56 S-D2（2026-09-26）：任务列表存储域（旧仓 utils/tasks.ts 848L 逐字
// 随迁 + Todo 型面 18L；Task 四件套 + TodoWrite 消费面，门控槽 ⑯ isTodoV2；
// zod→TS 型转录 / lockfile namespace 面 / getTeamsDir·uniq 域内本地 /
// growthbook killswitch 支裁等 delta 登记见 tasks/tasks.ts + todoTypes.ts +
// messaging/agentSwarmsEnabled.ts 头注）
export {
  setLeaderTeamName,
  clearLeaderTeamName,
  onTasksUpdated,
  notifyTasksUpdated,
  TASK_STATUSES,
  isTaskStatus,
  type Task,
  type TaskStatus,
  resetTaskList,
  isTodoV2Enabled,
  getTaskListId,
  sanitizePathComponent,
  getTasksDir,
  getTaskPath,
  createTask,
  getTask,
  updateTask,
  deleteTask,
  listTasks,
  blockTask,
  type ClaimTaskResult,
  type ClaimTaskOptions,
  claimTask,
  type TeamMember,
  type AgentStatus,
  getAgentStatuses,
  type UnassignTasksResult,
  unassignTeammateTasks,
  DEFAULT_TASKS_MODE_TASK_LIST_ID,
  type TodoStatus,
  type TodoItem,
  type TodoList,
} from './tasks'

// §8.56 S-D2：agent teams / swarms 总开关（messaging 域内文件，经域门面出）
export { isAgentSwarmsEnabled } from './messaging'
