/**
 * 基础工具 Read/Edit/Bash/Glob/Grep + AgentTool + 注册表 getAllBaseTools
 *
 * 实现波次: E-2 已落 AgentTool 核心（T-5b）+ MCP 构建（T-5a）+ 注册表机制
 *   getAllBaseTools(deps)（T-5e）；49 基础工具本体（47 = 历史口径，§8.53 审计④）= 残留守（各本体纵切经 deps 注入）——§8.54 S-B5 已落 BashTool + §8.55 S-C4 已落 GlobTool + GrepTool + S-C5 已落 ReadTool + S-C6 已落 WriteTool + EditTool = 6/49（43 剩，高频族全闭环 → 长尾 43 本体纵切后续波）。
 *
 * T-5a（§8.25 E-2）已落 MCP 工具构建面 → 在此 re-export；port 类型面
 *   （McpToolResult/McpToolClient/McpToolDescriptor/MCPServerConnection）归
 *   ports/mcpClient，经 engine 门面（engine/index.ts）单独 re-export。
 * T-5b（§8.25 E-2）已落 AgentTool 核心面 → 在此 re-export（agent/ 子门面）。
 * T-5d（§8.25 E-2）已落工具名常量 seed（toolNames：ASYNC/INTERNAL 集 + 单工具名）。
 * T-5e（§8.25 E-2）已落注册表机制 toolRegistry（getAllBaseTools(deps) deps 注入 +
 *   ASCEND 门控 + 按名去重）+ toolNames 全量常量集（4 工具名集 + 14 单工具名）。
 * E-4 S-4a（§8.31/§8.32）已落 LEGACY 工具名 alias 表 legacyToolNameAliases
 *   （4 项 legacy → 正规名，正规名引用 toolNames/agent 常量；模块加载注册
 *   进 permissions 域解析函数组，re-export 触发 side-effect import）。
 * E-4 S-4c1（§8.34 裁定 ⑤）已落 getToolsForDefaultPreset(deps)（机制面默认
 *   预设工具名，engine/permissions permissionSetup 传递依赖提前；本体残留守不变）。
 * E-4 S-4d（§8.36）已落 filterToolsByDenyRules + getTools（deny 规则工具面
 *   过滤，域 getDenyRuleForTool 消费；模式过滤支裁出见 toolRegistry 头注）。
 * §8.53 S-T1（工具本体波 C 桶 ①）已落 bash 内核 8 文件（旧仓 utils/bash 闭包
 *   子集逐字随迁）+ 4 本地小模块 → 在此 re-export（bash/ 子门面）。
 * §8.53 S-T2a 已落 bash checkPermissions 面 4 文件（旧仓 tools/BashTool
 *   bashSecurity/sedValidation/modeValidation/bashCommandHelpers 逐字随迁）
 *   + bashToolInput duck 型 → bash/ 子门面 re-export 扩块；残留守 bashPermissions
 *   / pathValidation / shouldUseSandbox = S-T2b。
 * §8.53 S-T2b 已落核心 3 文件 + 6 本地辅助模块 → bash/ 子门面 re-export 再扩块。
 * §8.54 S-B 子波（Bash 本体纵切）S-B1~S-B5 已落 9 文件本体 + 依赖闭包层 →
 *   在此 re-export（bash/ 子门面）；S-B5 落 BashTool 对象 = 49 基础工具本体
 *   首个纵切落地（残留守「49 本体」登记随之缩 1）+ 首个非-passthrough
 *   checkPermissions 工具面实现（§8.43 裁定① 闭环）。
 * §8.55 S-C 子波（高频族本体纵切）S-C1~S-C4 已落 files/ 子域依赖闭包层
 *   1/2/3 + Glob/Grep 本体 → 在此 re-export（files/ 子门面）；S-C4 落
 *   GlobTool + GrepTool 对象（残留守「49 本体」登记再缩 2 → 3/49）+
 *   checkPermissions 一线接线 checkReadPermissionForTool（搜索工具面
 *   读权限决策体消费，§8.55 裁定）；S-C5 落 ReadTool 本体（4/49）+
 *   S-C6 落 WriteTool + EditTool 本体（fileWriteTool/fileEditTool/
 *   fileEditUtils/fileEditConstants/fileWritePrompt/fileEditPrompt）
 *   → 6/49 波终态（高频族全闭环，43 长尾本体纵切后续波）。
 */
export {
  createMcpTools,
  findMcpServerConnection,
  buildMcpToolName,
  getMcpPrefix,
  mcpInfoFromString,
  normalizeNameForMCP,
} from './mcp'
export {
  getAllBaseTools,
  getToolsForDefaultPreset,
  filterToolsByDenyRules,
  getTools,
  isAscendToolsEnabled,
  TOOL_PRESETS,
  parseToolPreset,
  type ToolRegistryDeps,
  type ToolPreset,
} from './toolRegistry'
export {
  ASYNC_AGENT_ALLOWED_TOOLS,
  INTERNAL_WORKER_TOOLS,
  ALL_AGENT_DISALLOWED_TOOLS,
  CUSTOM_AGENT_DISALLOWED_TOOLS,
  IN_PROCESS_TEAMMATE_ALLOWED_TOOLS,
  COORDINATOR_MODE_ALLOWED_TOOLS,
  TASK_OUTPUT_TOOL_NAME,
  ENTER_PLAN_MODE_TOOL_NAME,
  EXIT_PLAN_MODE_V2_TOOL_NAME,
  ASK_USER_QUESTION_TOOL_NAME,
  TASK_CREATE_TOOL_NAME,
  TASK_GET_TOOL_NAME,
  TASK_LIST_TOOL_NAME,
  TASK_UPDATE_TOOL_NAME,
  CRON_CREATE_TOOL_NAME,
  CRON_DELETE_TOOL_NAME,
  CRON_LIST_TOOL_NAME,
  CONFIG_TOOL_NAME,
  WORKFLOW_TOOL_NAME,
  REPL_TOOL_NAME,
  BASH_TOOL_NAME,
  FILE_READ_TOOL_NAME,
  FILE_EDIT_TOOL_NAME,
  FILE_WRITE_TOOL_NAME,
  GREP_TOOL_NAME,
  GLOB_TOOL_NAME,
  WEB_SEARCH_TOOL_NAME,
  WEB_FETCH_TOOL_NAME,
  TODO_WRITE_TOOL_NAME,
  NOTEBOOK_EDIT_TOOL_NAME,
  SKILL_TOOL_NAME,
  SYNTHETIC_OUTPUT_TOOL_NAME,
  TOOL_SEARCH_TOOL_NAME,
  ENTER_WORKTREE_TOOL_NAME,
  EXIT_WORKTREE_TOOL_NAME,
  TEAM_CREATE_TOOL_NAME,
  TEAM_DELETE_TOOL_NAME,
  SEND_MESSAGE_TOOL_NAME,
  TASK_STOP_TOOL_NAME,
  SHELL_TOOL_NAMES,
} from './toolNames'
export { LEGACY_TOOL_NAME_ALIASES } from './legacyToolNameAliases'
export {
  AgentTool,
  runAgent,
  GENERAL_PURPOSE_AGENT,
  isBuiltInAgent,
  isCustomAgent,
  getBuiltInAgents,
  parseAgentFromMarkdown,
  getActiveAgentsFromList,
  loadAgentDefinitions,
  isForkSubagentEnabled,
  FORK_AGENT,
  buildForkedMessages,
  buildChildMessage,
  isInForkChild,
  buildWorktreeNotice,
  FORK_SUBAGENT_TYPE,
  FORK_BOILERPLATE_TAG,
  FORK_DIRECTIVE_PREFIX,
  computeChildSpawnDepth,
  filterToolsForAgent,
  resolveAgentTools,
  countToolUses,
  finalizeAgentTool,
  AGENT_TOOL_NAME,
  MAX_WORKER_SPAWN_DEPTH,
  getPrompt,
  formatAgentLine,
  type RunAgentArgs,
  type RunAgentResult,
  type AgentDefinition,
  type AgentToolResult,
  type ResolvedAgentTools,
  type InjectedAgentFile,
} from './agent'
export {
  type TsNode,
  ensureParserInitialized,
  getParserModule,
  SHELL_KEYWORDS,
  type Node,
  type ParsedCommandData,
  ensureInitialized,
  parseCommand,
  PARSE_ABORTED,
  parseCommandRaw,
  extractCommandArguments,
  type Redirect,
  type SimpleCommand,
  type ParseForSecurityResult,
  nodeTypeId,
  parseForSecurity,
  parseForSecurityFromAst,
  type SemanticCheckResult,
  checkSemantics,
  type CommandPrefixResult,
  type CommandSubcommandPrefixResult,
  splitCommandWithOperators,
  filterControlOperators,
  splitCommand_DEPRECATED,
  isHelpCommand,
  getCommandSubcommandPrefix,
  clearCommandPrefixCaches,
  isUnsafeCompoundCommand_DEPRECATED,
  extractOutputRedirections,
  type HeredocInfo,
  type HeredocExtractionResult,
  extractHeredocs,
  restoreHeredocs,
  containsHeredoc,
  type QuoteContext,
  type CompoundStructure,
  type DangerousPatterns,
  type TreeSitterAnalysis,
  extractQuoteContext,
  extractCompoundStructure,
  hasActualOperatorNodes,
  extractDangerousPatterns,
  analyzeCommand,
  type OutputRedirection,
  type IParsedCommand,
  RegexParsedCommand_DEPRECATED,
  buildParsedCommandFromRoot,
  ParsedCommand,
  type ShellParseResult,
  type ShellQuoteResult,
  tryParseShellCommand,
  tryQuoteShellArgs,
  hasMalformedTokens,
  hasShellQuoteSingleQuoteBug,
  quote,
  type PrefixExtractorConfig,
  type CommandPrefixExtractor,
  type SubcommandPrefixExtractor,
  createCommandPrefixExtractor,
  createSubcommandPrefixExtractor,
  // ── S-T2a（§8.53）：checkPermissions 面 ──
  stripSafeHeredocSubstitutions,
  hasSafeHeredocSubstitution,
  bashCommandIsSafe_DEPRECATED,
  bashCommandIsSafeAsync_DEPRECATED,
  isLinePrintingCommand,
  isPrintCommand,
  sedCommandIsAllowedByAllowlist,
  hasFileArgs,
  extractSedExpressions,
  checkSedConstraints,
  checkPermissionMode,
  getAutoAllowedCommands,
  type CommandIdentityCheckers,
  checkCommandOperatorPermissions,
  type BashToolInput,
  // ── S-T2b（§8.53）：核心 3 文件 + 6 本地辅助模块 ──
  MAX_SUBCOMMANDS_FOR_SECURITY_CHECK,
  MAX_SUGGESTED_RULES_FOR_COMPOUND,
  BINARY_HIJACK_VARS,
  bashPermissionRule,
  bashToolCheckExactMatchPermission,
  bashToolCheckPermission,
  bashToolHasPermission,
  checkCommandAndSuggestRules,
  commandHasAnyCd,
  clearSpeculativeChecks,
  consumeSpeculativeClassifierCheck,
  awaitClassifierAutoApproval,
  executeAsyncClassifierCheck,
  getFirstWordPrefix,
  getSimpleCommandPrefix,
  isNormalizedCdCommand,
  isNormalizedGitCommand,
  matchWildcardPattern,
  peekSpeculativeClassifierCheck,
  startSpeculativeClassifierCheck,
  stripAllLeadingEnvVars,
  stripSafeWrappers,
  type PathCommand,
  PATH_EXTRACTORS,
  COMMAND_OPERATION_TYPE,
  createPathChecker,
  checkPathConstraints,
  stripWrappersFromArgv,
  shouldUseSandbox,
  isReadOnlyCommand,
  AbortError,
  type Platform,
  getPlatform,
  count,
  windowsPathToPosixPath,
  getDirectoryForPath,
  type BashToolUseContext,
  // ── S-B1（§8.54）：依赖闭包层 ──
  type FlagArgType,
  type ExternalCommandConfig,
  GIT_READ_ONLY_COMMANDS,
  GH_READ_ONLY_COMMANDS,
  DOCKER_READ_ONLY_COMMANDS,
  RIPGREP_READ_ONLY_COMMANDS,
  PYRIGHT_READ_ONLY_COMMANDS,
  EXTERNAL_READONLY_COMMANDS,
  containsVulnerableUncPath,
  FLAG_PATTERN,
  validateFlagArgument,
  validateFlags,
  isCurrentDirectoryBareGitRepo,
  getDefaultBashTimeoutMs,
  getMaxBashTimeoutMs,
  hasEmbeddedSearchTools,
  shouldMaintainProjectWorkingDir,
  shouldIncludeGitInstructions,
  prependBullets,
  // ── S-B2（§8.54）：纯叶子本体 ──
  extractBashCommentLabel,
  getDestructiveCommandWarning,
  type CommandSemantic,
  interpretCommandResult,
  type SedEditInfo,
  isSedInPlaceEdit,
  parseSedEditCommand,
  applySedSubstitution,
  stripEmptyLines,
  isImageOutput,
  parseDataUri,
  buildImageToolResult,
  resizeShellImageOutput,
  formatOutput,
  stdErrAppendShellResetMessage,
  resetCwdIfOutsideProject,
  createContentSummary,
  // ── S-B3（§8.54）：只读命令校验本体 ──
  isCommandSafeViaFlagParsing,
  checkReadOnlyConstraints,
  // ── S-B4（§8.54）：prompt 本体 ──
  getDefaultTimeoutMs,
  getMaxTimeoutMs,
  getSimplePrompt,
  // ── S-B5（§8.54）：BashTool 本体（首个非-passthrough checkPermissions 面）──
  BASH_TOOL_INPUT_SCHEMA,
  BashTool,
  getBackgroundTask,
  listBackgroundTasks,
  type Out,
  type BgTask,
} from './bash'
// ── S-C 子波（§8.55）：files 子域（S-C1~S-C3 依赖闭包层 + S-C4 Glob/Grep 本体）──
export {
  // S-C1：依赖闭包层 1
  PDF_TARGET_RAW_SIZE,
  PDF_EXTRACT_SIZE_THRESHOLD,
  PDF_MAX_EXTRACT_SIZE,
  PDF_MAX_PAGES_PER_READ,
  PDF_AT_MENTION_INLINE_THRESHOLD,
  CONTEXT_LINES,
  DIFF_TIMEOUT_MS,
  adjustHunkLineNumbers,
  countLinesChanged,
  getPatchFromContents,
  getPatchForDisplay,
  type FileEditInput,
  type EditInput,
  type FileEdit,
  fileReadCache,
  type LineEndingType,
  detectEncodingForResolvedPath,
  detectLineEndingsForString,
  readFileSyncWithMetadata,
  readFileSync,
  type File,
  pathExists,
  MAX_OUTPUT_SIZE,
  readFileSafe,
  getFileModificationTime,
  getFileModificationTimeAsync,
  writeTextContent,
  detectFileEncoding,
  detectLineEndings,
  convertLeadingTabsToSpaces,
  getAbsoluteAndRelativePaths,
  getDisplayPath,
  findSimilarFile,
  FILE_NOT_FOUND_CWD_NOTE,
  suggestPathUnderCwd,
  isCompactLinePrefixEnabled,
  addLineNumbers,
  stripLineNumberPrefix,
  isDirEmpty,
  readFileSyncCached,
  writeFileSyncAndFlush_DEPRECATED,
  getDesktopPath,
  isFileWithinReadSizeLimit,
  normalizePathForComparison,
  pathsEqual,
  semanticToNumber,
  semanticToBoolean,
  getMainLoopModelName,
  getCanonicalModelName,
  // S-C2：依赖闭包层 2
  normalizePatternsToPath,
  getFileReadIgnorePatterns,
  extractGlobBaseDirectory,
  glob,
  // S-C3：pdf/notebook 族
  execFileNoThrow,
  type PDFError,
  type PDFResult,
  type PDFExtractPagesResult,
  readPDF,
  getPDFPageCount,
  resetPdftoppmCache,
  isPdftoppmAvailable,
  extractPDFPages,
  DOCUMENT_EXTENSIONS,
  parsePDFPageRange,
  isPDFSupported,
  isPDFExtension,
  readNotebook,
  mapNotebookCellsToToolResult,
  parseCellId,
  type NotebookCellType,
  type NotebookCell,
  type NotebookDocument,
  NotebookCellKind,
  type NotebookContent,
  type NotebookCellSource,
  type NotebookCellSourceOutput,
  type NotebookOutputImage,
  type NotebookCellOutput,
  // S-C4：Glob/Grep 本体
  GLOB_DESCRIPTION,
  getGrepDescription,
  toRelativePath,
  type GlobToolInput,
  type GrepToolInput,
  type FilesToolUseContext,
  GLOB_TOOL_INPUT_SCHEMA,
  GlobTool,
  type GlobOutput,
  GREP_TOOL_INPUT_SCHEMA,
  GrepTool,
  type GrepOutput,
  // S-C5：Read 本体
  BINARY_EXTENSIONS,
  hasBinaryExtension,
  isBinaryContent,
  DEFAULT_MAX_OUTPUT_TOKENS,
  getDefaultFileReadingLimits,
  type FileReadingLimits,
  FILE_UNCHANGED_STUB,
  MAX_LINES_TO_READ,
  DESCRIPTION,
  LINE_FORMAT_INSTRUCTION,
  OFFSET_INSTRUCTION_DEFAULT,
  OFFSET_INSTRUCTION_TARGETED,
  renderPromptTemplate,
  type InDomainUserMessage,
  createUserMessage,
  memoryAgeDays,
  memoryAge,
  memoryFreshnessText,
  memoryFreshnessNote,
  READ_TOOL_INPUT_SCHEMA,
  ReadTool,
  type ReadOutput,
  MaxFileReadTokenExceededError,
  registerFileReadListener,
  CYBER_RISK_MITIGATION_REMINDER,
  type ReadToolInput,
  type FileState,
  type ReadFileState,
  // S-C6：Write+Edit 本体
  ATLAS_FOLDER_PERMISSION_PATTERN,
  GLOBAL_ATLAS_FOLDER_PERMISSION_PATTERN,
  FILE_UNEXPECTEDLY_MODIFIED_ERROR,
  LEFT_SINGLE_CURLY_QUOTE,
  RIGHT_SINGLE_CURLY_QUOTE,
  LEFT_DOUBLE_CURLY_QUOTE,
  RIGHT_DOUBLE_CURLY_QUOTE,
  normalizeQuotes,
  stripTrailingWhitespace,
  findActualString,
  preserveQuoteStyle,
  applyEditToFile,
  getPatchForEdit,
  getPatchForEdits,
  getSnippetForTwoFileDiff,
  getSnippetForPatch,
  getSnippet,
  getEditsForPatch,
  normalizeFileEditInput,
  areFileEditsEquivalent,
  areFileEditsInputsEquivalent,
  getEditToolDescription,
  getWriteToolDescription,
  WRITE_TOOL_INPUT_SCHEMA,
  WriteTool,
  type WriteOutput,
  EDIT_TOOL_INPUT_SCHEMA,
  EditTool,
  type EditOutput,
  type WriteToolInput,
} from './files'
