export const logHandler : any = (() => ({})) as any;
export const errorHandler : any = (() => ({})) as any;
export const exportHandler : any = (() => ({})) as any;
export const taskCreateHandler : any = (() => ({})) as any;
export const taskListHandler : any = (() => ({})) as any;
export const taskGetHandler : any = (() => ({})) as any;
export const taskUpdateHandler : any = (() => ({})) as any;
export const taskDirHandler : any = (() => ({})) as any;
export const completionHandler : any = (() => ({})) as any;
